### ISSUE TITLE
Windows Backup failed in Browser, works with php artisan backup:run

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/BackupManager#63]
# Bug report
No error is returned

### What I did:
I installed the package and configured

I tried the command in the prompt
php artisan backup: run
the backup is started

config/backup.php
`return [
    'backup' => [
        'backpack_flags' => [
            '--disable-notifications'=> false,
        ],
        'name' => env('APP_URL'),
        'source' => [
            'files' => [
                'include' => [
                    base_path(),
                ],
                'exclude' => [
                    base_path('vendor'),
                    storage_path(),
                ],
                'followLinks' => false,
            ],
            'databases' => [
                'mysql',
            ],
        ],
        'gzip_database_dump' => false,
        'destination' => [
            'filename_prefix' => '',
            'disks' => [
                'backups',
            ],
        ],
        'temporary_directory' => storage_path('app/backup-temp'),
    ],
    'notifications' => [
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => [],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => [],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => [],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => [],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => [],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => [],
        ],
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,
        'mail' => [
            'to'   => 'your@email.com',
        ],
        'slack' => [
            'webhook_url' => '',
            'channel' => null,
        ],
    ],
    'monitorBackups' => [
        [
            'name'                                   => env('APP_NAME'),
            'disks'                                  => ['backups'],
            'newestBackupsShouldNotBeOlderThanDays'  => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 5000,
        ],
    ],

    'cleanup' => [
        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,
        'defaultStrategy' => [
            'keepAllBackupsForDays' => 7,
            'keepDailyBackupsForDays' => 16,
            'keepWeeklyBackupsForWeeks' => 8,
            'keepMonthlyBackupsForMonths' => 4,
            'keepYearlyBackupsForYears' => 2,
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
    ],
];
`

config/database.php
`
...
'dump' => [
                //'dump_binary_path' => '/path/to/the/binary', // only the path, so without `mysqldump` or `pg_dump`
                'dump_binary_path' => 'C:\Programmi\MySQL\MySQL Server 8.0\bin',
...
`
### What I expected to happen:
I expected that by clicking on the button create a new backup, the process would start.

### What happened:
The process seems to start but in reality nothing happens
Log Result:
local.INFO: Backpack\BackupManager -- Called backup:run from admin interface  
local.INFO: Backpack\BackupManager -- backup process has started  

### What I've already tried to fix it:

vendor\backpack\backupmanager\src\app\Http\Controllers\BackupController.php

`
    public function create()
    {
        try {
            ini_set('max_execution_time', 600);

            Log::info('Backpack\BackupManager -- Called backup:run from admin interface');

            ---$process = new Process('php artisan backup:run');
            +++$process = new Process('php artisan backup:run',base_path());
            $process->start();
            Log::info("Backpack\BackupManager -- backup process has started");
            
          +++  while ($process->isRunning()) {
          +++      sleep(10);
          +++  }
          +++  Log::info("Backpack\BackupManager -- backup process has fineshed");
        } catch (Exception $e) {
            Response::make($e->getMessage(), 500);
        }

        return 'success';
    }
`
The backup is started

### Backpack, Laravel, PHP, DB version:
laravel/framework                     v5.8.7
backpack/base                         1.1.4
backpack/crud                         3.6.6
backpack/backupmanager      1.4.7

PHP Version 7.3.3
MySQL Server 8.0

**Comment by tabacitu** [comment]
Hi @xdasty ,

Just pushed a fix a few days ago. Previously we were calling the command manually, now we're calling it through the Artisan class. A ```composer update``` should fix it for you. Let me know if it doesn't.

Cheers!

**Comment by xdasty** [comment]
I've tested it works perfectly now.

Always congratulations, for the job.

**Comment by 7dir** [comment]
```
$ php artisan backup:run                                                                                                                                                                                                                      
Starting backup...                                                                                                                                                                                                                            
Dumping database lara_admin...                                                                                                                                                                                                                
Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,                                                                                           
operable program or batch file.                                                                                                                                                                                                               
.                                                                                                                                                                                                                                             
#0 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\db-dumper\src\DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))                                       
#1 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\db-dumper\src\Databases\MySql.php(190): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'F:\\ga\\prjs\\Rkee...')                        
#2 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(250): Spatie\DbDumper\Databases\MySql->dumpToFile('F:\\ga\\prjs\\Rkee...')                                                              
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')                                                                                          
#4 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Support\Collection.php(1120): array_map(Object(Closure), Array, Array)                                                                                      
#5 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(253): Illuminate\Support\Collection->map(Object(Closure))                                                                               
#6 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()                                                                             
#7 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()                                                                      
#8 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()                                                                                        
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()                                                                                                                                                                        
#10 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array(Array, Array)                                                                                          
#11 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()                                                          
#12 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))        
#13 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Container\Container.php(576): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)                        
#14 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call(Array)                                                                                      
#15 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))                    
#16 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\Outpu
tStyle))                                                                                                                                                                                                                                      
#17 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOu
tput))                                                                                                                                                                                                                                        
#18 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\symfony\console\Application.php(921): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))    
#19 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), O
bject(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                                                                        
#20 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)
)                                                                                                                                                                                                                                             
#21 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Console\Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console
\Output\ConsoleOutput))                                                                                                                                                                                                                       
#22 F:\ga\prjs\Rkeeper7\laravel\lara_admin\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(133): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console
\Output\ConsoleOutput))                                                                                                                                                                                                                       
#23 F:\ga\prjs\Rkeeper7\laravel\lara_admin\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                               
#24 {main}                                                                                                                                                                                                                                    
Backup failed because: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required                                                                                                                         
".                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
```

**Comment by 7dir** [comment]
> mysqldump

**Comment by 7dir** [comment]
.env 

```

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com    
MAIL_PORT=465    
MAIL_USERNAME=USER@gmail.com
MAIL_PASSWORD=PASS
MAIL_ENCRYPTION=ssl
```
